application: fantasy-moneyball
version: 1
runtime: python27
api_version: 1
threadsafe: true
libraries:
 - name: jinja2
   version: latest
 - name: markupsafe
   version: latest
 - name: PIL
   version: "1.1.7"

handlers:
 - url: /?.*
   script: main.app

builtins:
 - remote_api: on
